### ISSUE TITLE
compilation failure

### ISSUE THREAD

**Issue by githubgnulinux** [tomka/cliaspora#4]
unzip .../cliaspora-master.zip 
Archive:  .../cliaspora-master.zip
...478
   creating: cliaspora-master/
 extracting: cliaspora-master/AUTHORS  
  inflating: cliaspora-master/Makefile  
  inflating: cliaspora-master/README.md  
  inflating: cliaspora-master/cliaspora.1  
  inflating: cliaspora-master/cliaspora.c  
  inflating: cliaspora-master/config.c  
  inflating: cliaspora-master/config.h  
  inflating: cliaspora-master/contacts.c  
  inflating: cliaspora-master/file.c  
  inflating: cliaspora-master/file.h  
  inflating: cliaspora-master/http.c  
  inflating: cliaspora-master/http.h  
  inflating: cliaspora-master/json.c  
  inflating: cliaspora-master/json.h  
  inflating: cliaspora-master/readpass.c  
  inflating: cliaspora-master/ssl.c  
  inflating: cliaspora-master/ssl.h  
  inflating: cliaspora-master/str.c  
  inflating: cliaspora-master/str.h  
  inflating: cliaspora-master/types.h  
.../usr/local/cliaspora$ cd cliaspora-master/
.../usr/local/cliaspora/cliaspora-master$ less README.md 

.../usr/local/cliaspora/cliaspora-master$ && make install
bash: syntax error near unexpected token `&&'
.../usr/local/cliaspora/cliaspora-master$ make install
cc -o cliaspora -std=c99 -Wall -DPROGRAM=\"cliaspora\" cliaspora.c config.c ssl.c http.c json.c file.c readpass.c str.c -lssl -lcrypto
In file included from cliaspora.c:42:0:
ssl.h:28:26: fatal error: openssl/rand.h: No such file or directory
 #include <openssl/rand.h>
                          ^
compilation terminated.
In file included from ssl.c:43:0:
ssl.h:28:26: fatal error: openssl/rand.h: No such file or directory
 #include <openssl/rand.h>
                          ^
compilation terminated.
In file included from http.c:37:0:
ssl.h:28:26: fatal error: openssl/rand.h: No such file or directory
 #include <openssl/rand.h>
                          ^
compilation terminated.
Makefile:13: recipe for target 'cliaspora' failed
make: *** [cliaspora] Error 1

**Comment by noplanman** [comment]
Make sure you have OpenSSL installed.
Also, for it to work on never versions of diaspora\* you will need to change the source to use the new CSRF meta tag.
Check this commit on my fork: https://github.com/noplanman/cliaspora/commit/adcbcf0468ecd4451e795162de1cf31b05fc29c7

**Comment by tomka** [comment]
Like @noplanman, I would suggest to make sure OpenSSL installed (as well as its dev packages if your distro uses these). Please also note that I don't maintain this project actively and this repo is merely a mirror of the original source code.

**Comment by githubgnulinux** [comment]
As advised in diaspora post, compilation successful after installation of libssl-dev.
